name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Debug package files
        run: |
          echo "=== Package.json ==="
          cat package.json | head -20
          echo ""
          echo "=== Package-lock.json exists ==="
          ls -la package-lock.json
          echo ""
          echo "=== Node version ==="
          node --version
          echo ""
          echo "=== NPM version ==="
          npm --version

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run tests with coverage
        run: npm test
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL || 'https://test.supabase.co' }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY || 'test-key' }}

      - name: Run Expo Doctor
        run: npx expo-doctor
        continue-on-error: true

      - name: CI Summary
        if: always()
        run: |
          echo "### CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ All CI checks completed!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Type Check: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- Linting: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- Tests: Completed" >> $GITHUB_STEP_SUMMARY
          echo "- Expo Doctor: Completed" >> $GITHUB_STEP_SUMMARY

